import type { DataPlugin, Offer, Product, Store, Trend } from "../core/types";

const now = "2026-05-21T12:00:00.000Z";

export const stores: Store[] = [
  { id: "momo", name: "momo", kind: "marketplace", url: "https://www.momoshop.com.tw/" },
  { id: "shopee", name: "蝦皮購物", kind: "marketplace", url: "https://shopee.tw/" },
  { id: "pchome", name: "PChome 24h", kind: "retailer", url: "https://24h.pchome.com.tw/" },
  { id: "coupang", name: "酷澎", kind: "marketplace", url: "https://www.tw.coupang.com/" },
  { id: "apple", name: "Apple 官方", kind: "brand", url: "https://www.apple.com/tw/" },
  { id: "biggo", name: "BigGo", kind: "comparison", url: "https://biggo.com.tw/" },
  { id: "feebee", name: "飛比價格", kind: "comparison", url: "https://feebee.com.tw/" },
  { id: "iherb", name: "iHerb", kind: "cross-border", url: "https://tw.iherb.com/" },
  { id: "mercari", name: "Mercari JP", kind: "cross-border", url: "https://jp.mercari.com/" },
  { id: "brand-store", name: "品牌官方旗艦", kind: "brand", url: "https://example.com/brand-store" },
];

export const products: Product[] = [
  {
    slug: "iphone-17-256",
    name: "iPhone 17 256GB",
    categoryId: "phones",
    summary: "高搜尋量旗艦手機，適合比較空機、電信方案與官方保固。",
    keywords: ["iphone 17", "iphone 17 256gb", "蘋果手機", "空機"],
    image: "phones",
    specs: { 容量: "256GB", 保固: "台灣公司貨優先", 重點: "空機價差與電信補貼" },
    buyingAdvice: "若價差小於 5%，優先挑官方或授權通路；若搭門號，需把月租總成本一起比較。",
  },
  {
    slug: "iphone-17-pro-256",
    name: "iPhone 17 Pro 256GB",
    categoryId: "phones",
    summary: "高單價 Pro 機型，價差足以支撐獨立 SEO 比價頁。",
    keywords: ["iphone 17 pro", "iphone 17 pro 256gb", "空機", "apple"],
    image: "phones",
    specs: { 容量: "256GB", 族群: "攝影與高效能需求", 重點: "通路折扣與贈品價值" },
    buyingAdvice: "Pro 機型常有贈品與刷卡回饋，建議用現金價、回饋後價格與保固來源三軸比較。",
  },
  {
    slug: "iphone-16-128",
    name: "iPhone 16 128GB",
    categoryId: "phones",
    summary: "前代 iPhone 具備降價與庫存紅利，適合做性價比比較。",
    keywords: ["iphone 16", "iphone 16 128gb", "前代 iphone"],
    image: "phones",
    specs: { 容量: "128GB", 族群: "預算型換機", 重點: "前代降價幅度" },
    buyingAdvice: "若不追求最新功能，前代機型的現金價通常更值得觀察。",
  },
  {
    slug: "galaxy-s26-ultra",
    name: "Samsung Galaxy S26 Ultra",
    categoryId: "phones",
    summary: "Android 旗艦代表，適合比較首購禮、通路價與舊換新。",
    keywords: ["samsung s26 ultra", "galaxy s26 ultra", "三星旗艦"],
    image: "phones",
    specs: { 品牌: "Samsung", 族群: "Android 旗艦", 重點: "首購禮與舊換新" },
    buyingAdvice: "三星旗艦常把優惠藏在贈品與舊換新，頁面需拆出實付價與等值回饋。",
  },
  {
    slug: "airpods-pro",
    name: "AirPods Pro",
    categoryId: "phones",
    summary: "熱門耳機長尾關鍵字，適合比較官方、電商與跨境價。",
    keywords: ["airpods pro", "蘋果耳機", "降噪耳機"],
    image: "phones",
    specs: { 類型: "真無線耳機", 特色: "主動降噪", 重點: "保固與版本" },
    buyingAdvice: "耳機需注意平行輸入與保固地區，最低價不一定是最佳選擇。",
  },
  {
    slug: "magsafe-power-bank",
    name: "MagSafe 行動電源",
    categoryId: "phones",
    summary: "手機周邊轉換率高，適合用容量、重量與磁吸穩定度比較。",
    keywords: ["magsafe 行動電源", "磁吸行動電源", "iphone 配件"],
    image: "phones",
    specs: { 容量: "5000-10000mAh", 特色: "磁吸無線充電", 重點: "安全認證" },
    buyingAdvice: "優先挑有 BSMI 與過熱保護的款式，不只看容量與價格。",
  },
  {
    slug: "face-sunscreen",
    name: "臉部防曬乳",
    categoryId: "summer",
    summary: "momo 5 月熱搜與夏季剛需題材，適合品牌與膚質篩選。",
    keywords: ["臉部防曬", "防曬乳", "防曬推薦"],
    image: "summer",
    specs: { SPF: "SPF50+ 常見", 膚質: "油肌/敏感肌/乾肌", 重點: "單 ml 價格" },
    buyingAdvice: "防曬建議比較每 ml 價格、膚感與是否防水，回購品可優先看組合包。",
  },
  {
    slug: "body-sunscreen",
    name: "身體防曬",
    categoryId: "summer",
    summary: "夏日戶外與旅遊需求增加，容量與單位價格很重要。",
    keywords: ["身體防曬", "防曬乳", "戶外防曬"],
    image: "summer",
    specs: { 容量: "大容量優先", 場景: "戶外/海邊/通勤", 重點: "防水與清爽度" },
    buyingAdvice: "身體防曬消耗快，建議優先比較大容量與組合價。",
  },
  {
    slug: "uv-jacket",
    name: "抗 UV 防曬外套",
    categoryId: "summer",
    summary: "夏季機能服飾上升關鍵字，適合用 UPF、透氣與重量比較。",
    keywords: ["防曬外套", "抗uv防曬外套", "涼感外套"],
    image: "summer",
    specs: { 防護: "UPF50+ 常見", 材質: "涼感/透氣", 重點: "尺寸與版型" },
    buyingAdvice: "機能服飾要把 UPF 標示、透氣性與尺寸退換貨政策一起看。",
  },
  {
    slug: "cooling-bed-sheet",
    name: "涼感床包",
    categoryId: "summer",
    summary: "換季寢具熱搜品類，價格差異來自材質與尺寸。",
    keywords: ["涼感床包", "涼感床墊", "涼感寢具"],
    image: "summer",
    specs: { 尺寸: "單人/雙人/加大", 材質: "尼龍/嫘縈/聚酯", 重點: "Q-max 或涼感標示" },
    buyingAdvice: "寢具要按尺寸與件數換算，避免不同組合包造成誤判。",
  },
  {
    slug: "cooling-blanket",
    name: "涼被",
    categoryId: "summer",
    summary: "夏季高轉換品類，適合做尺寸、重量與可機洗比較。",
    keywords: ["涼被", "涼感被", "夏被"],
    image: "summer",
    specs: { 尺寸: "單人/雙人", 清潔: "可機洗優先", 重點: "重量與透氣" },
    buyingAdvice: "比價時要確認是否包含枕套或床包，避免只比較單件價格。",
  },
  {
    slug: "sheet-mask",
    name: "保濕面膜",
    categoryId: "summer",
    summary: "防曬修復與美妝季節題材，可用每片價格與成分比較。",
    keywords: ["面膜", "保濕面膜", "曬後修復"],
    image: "summer",
    specs: { 類型: "片狀面膜", 重點: "每片價格", 成分: "保濕/舒緩" },
    buyingAdvice: "面膜要以每片價格比較，並標示是否為效期品或大量組合包。",
  },
  {
    slug: "robot-vacuum",
    name: "掃拖機器人",
    categoryId: "home-appliances",
    summary: "高單價、規格差異大的家電比價主題。",
    keywords: ["掃拖機器人", "掃地機器人", "洗地機器人"],
    image: "home",
    specs: { 功能: "自動集塵/洗拖布", 重點: "避障與耗材", 場景: "家庭清潔" },
    buyingAdvice: "掃拖機器人要把耗材、保固與維修據點納入總成本。",
  },
  {
    slug: "wet-dry-vacuum",
    name: "洗地機",
    categoryId: "home-appliances",
    summary: "momo 春季清潔熱搜，價格帶廣且品牌差異明顯。",
    keywords: ["洗地機", "無線洗地機", "乾濕兩用吸塵器"],
    image: "home",
    specs: { 類型: "乾濕兩用", 重點: "自清潔與重量", 場景: "硬地板" },
    buyingAdvice: "洗地機最常被忽略的是重量與清潔水箱容量，建議比價格也比日常使用負擔。",
  },
  {
    slug: "inverter-dehumidifier",
    name: "變頻除濕機",
    categoryId: "home-appliances",
    summary: "台灣長年剛需家電，適合比較除濕力、能源效率與補助。",
    keywords: ["除濕機", "變頻除濕機", "冷氣補助"],
    image: "home",
    specs: { 除濕力: "12-22L/日", 重點: "能源效率", 場景: "潮濕居家" },
    buyingAdvice: "除濕機建議按坪數、能源效率與是否符合補助資格來比較。",
  },
  {
    slug: "cordless-vacuum",
    name: "無線吸塵器",
    categoryId: "home-appliances",
    summary: "品牌與吸力規格差異明顯，適合做規格導購。",
    keywords: ["無線吸塵器", "dyson 吸塵器", "吸塵器推薦"],
    image: "home",
    specs: { 類型: "無線手持", 重點: "續航與重量", 場景: "日常清潔" },
    buyingAdvice: "吸塵器要比較主機重量、電池可替換性與配件數量。",
  },
  {
    slug: "air-purifier",
    name: "空氣清淨機",
    categoryId: "home-appliances",
    summary: "季節與空污話題會帶動搜尋，耗材成本是比價重點。",
    keywords: ["空氣清淨機", "hepa", "空氣清淨機推薦"],
    image: "home",
    specs: { 濾網: "HEPA 常見", 重點: "CADR 與耗材", 場景: "客廳/臥室" },
    buyingAdvice: "清淨機需把濾網年成本加入比較，低機身價不一定划算。",
  },
  {
    slug: "vacuum-storage-bag",
    name: "真空壓縮袋",
    categoryId: "home-appliances",
    summary: "春季收納與換季關鍵字，適合做尺寸與入數比較。",
    keywords: ["真空壓縮袋", "衣物收納袋", "收納用品"],
    image: "home",
    specs: { 入數: "多入組", 重點: "單個價格", 場景: "換季收納" },
    buyingAdvice: "收納用品要比較單個價格與尺寸，避免入數不同造成錯覺。",
  },
  {
    slug: "lutein",
    name: "葉黃素",
    categoryId: "health",
    summary: "保健品回購關鍵字，適合做每份劑量與每日成本比較。",
    keywords: ["葉黃素", "葉黃素推薦", "保健食品"],
    image: "health",
    specs: { 劑量: "10-20mg 常見", 重點: "每日成本", 場景: "長時間用眼" },
    buyingAdvice: "保健品不要只看瓶價，應換算每份有效成分與每日成本。",
  },
  {
    slug: "probiotics",
    name: "益生菌",
    categoryId: "health",
    summary: "高回購保健品，品牌與菌株訴求多，適合內容導購。",
    keywords: ["益生菌", "益生菌推薦", "保健食品"],
    image: "health",
    specs: { 類型: "粉包/膠囊", 重點: "每包價格", 場景: "日常保健" },
    buyingAdvice: "益生菌建議比較菌株資訊、保存方式與每包價格。",
  },
  {
    slug: "fish-oil",
    name: "魚油",
    categoryId: "health",
    summary: "跨境與本地通路都有需求，可用 EPA/DHA 含量比較。",
    keywords: ["魚油", "omega 3", "魚油推薦"],
    image: "health",
    specs: { 成分: "EPA/DHA", 重點: "每份有效含量", 場景: "日常保健" },
    buyingAdvice: "魚油要看每份 EPA/DHA，而不是只看膠囊數。",
  },
  {
    slug: "vitamin-d",
    name: "維生素 D",
    categoryId: "health",
    summary: "低單價但搜尋長尾穩定，適合跨境平台內容頁。",
    keywords: ["維生素 d", "vitamin d", "保健食品"],
    image: "health",
    specs: { 劑量: "1000-2000 IU 常見", 重點: "每顆價格", 場景: "日常補充" },
    buyingAdvice: "低單價保健品可透過組合購買攤平運費。",
  },
  {
    slug: "chiikawa-blind-box",
    name: "吉伊卡哇盲盒",
    categoryId: "ip-goods",
    summary: "IP 熱度高，適合用內容頁提醒授權、版本與溢價。",
    keywords: ["吉伊卡哇", "chiikawa", "盲盒"],
    image: "ip",
    specs: { 類型: "盲盒/公仔", 重點: "授權與版本", 風險: "溢價與仿品" },
    buyingAdvice: "IP 商品建議優先標示官方授權與現貨/預購，避免只追低價。",
  },
  {
    slug: "labubu",
    name: "Labubu 公仔",
    categoryId: "ip-goods",
    summary: "話題 IP 商品，價格波動與真假貨風險都高。",
    keywords: ["labubu", "拉布布", "公仔"],
    image: "ip",
    specs: { 類型: "公仔/盲盒", 重點: "版本與來源", 風險: "仿品與炒價" },
    buyingAdvice: "Labubu 應把官方店、二級市場與預購期分開比較。",
  },
  {
    slug: "haikyuu-merch",
    name: "排球少年周邊",
    categoryId: "ip-goods",
    summary: "動漫 IP 長尾穩定，適合導向跨境與授權店比較。",
    keywords: ["排球少年", "動漫周邊", "haikyuu"],
    image: "ip",
    specs: { 類型: "壓克力/徽章/服飾", 重點: "官方授權", 來源: "台灣/日本" },
    buyingAdvice: "動漫周邊要注意預購期、版本與國際運費。",
  },
  {
    slug: "iherb-supplements",
    name: "iHerb 保健食品",
    categoryId: "cross-border",
    summary: "跨境保健品平台，適合做折扣碼、運費與報關提醒。",
    keywords: ["iherb", "iherb 優惠", "跨境保健品"],
    image: "cross-border",
    specs: { 平台: "iHerb", 重點: "折扣碼與運費", 注意: "報關與配送" },
    buyingAdvice: "跨境保健品要把折扣碼、運費、配送時間與報關限制一起看。",
  },
  {
    slug: "mercari-jp-proxy",
    name: "Mercari 日本代購",
    categoryId: "cross-border",
    summary: "二手日貨與稀有 IP 商品常見來源，適合做代購成本拆解。",
    keywords: ["mercari", "mercari 代購", "日本二手"],
    image: "cross-border",
    specs: { 平台: "Mercari JP", 重點: "代購費與國際運費", 風險: "商品狀態" },
    buyingAdvice: "Mercari 應拆出商品價、代購費、國際運費與可能稅費。",
  },
  {
    slug: "1688-household",
    name: "1688 居家小物",
    categoryId: "cross-border",
    summary: "上游低價平台，適合做批量、集運與品質風險內容。",
    keywords: ["1688", "1688 台灣", "居家小物"],
    image: "cross-border",
    specs: { 平台: "1688", 重點: "集運與最低採購量", 風險: "品質落差" },
    buyingAdvice: "1688 比價要把最小採購量、集運費與退貨難度納入。",
  },
];

const offerRows: Array<[string, string, number, string[]?]> = [
  ["iphone-17-256", "apple", 29900, ["official"]],
  ["iphone-17-256", "momo", 28690, ["coupon", "fast-delivery"]],
  ["iphone-17-256", "shopee", 27990, ["lowest"]],
  ["iphone-17-pro-256", "apple", 39900, ["official"]],
  ["iphone-17-pro-256", "momo", 38890, ["fast-delivery"]],
  ["iphone-17-pro-256", "shopee", 37880, ["lowest", "coupon"]],
  ["iphone-16-128", "pchome", 22990, ["fast-delivery"]],
  ["iphone-16-128", "momo", 22490, ["coupon"]],
  ["iphone-16-128", "shopee", 21690, ["lowest"]],
  ["galaxy-s26-ultra", "momo", 32990, ["fast-delivery"]],
  ["galaxy-s26-ultra", "pchome", 31990, ["coupon"]],
  ["galaxy-s26-ultra", "shopee", 31430, ["lowest"]],
  ["airpods-pro", "apple", 7490, ["official"]],
  ["airpods-pro", "momo", 6990, ["fast-delivery"]],
  ["airpods-pro", "coupang", 6680, ["lowest"]],
  ["magsafe-power-bank", "momo", 1490, ["fast-delivery"]],
  ["magsafe-power-bank", "shopee", 1190, ["lowest"]],
  ["magsafe-power-bank", "pchome", 1390, ["free-shipping"]],
  ["face-sunscreen", "momo", 899, ["coupon"]],
  ["face-sunscreen", "coupang", 759, ["lowest", "fast-delivery"]],
  ["face-sunscreen", "shopee", 820, ["free-shipping"]],
  ["body-sunscreen", "momo", 699, ["coupon"]],
  ["body-sunscreen", "coupang", 599, ["lowest"]],
  ["body-sunscreen", "shopee", 650, ["free-shipping"]],
  ["uv-jacket", "momo", 1280, ["coupon"]],
  ["uv-jacket", "shopee", 899, ["lowest"]],
  ["uv-jacket", "pchome", 1180, ["fast-delivery"]],
  ["cooling-bed-sheet", "momo", 1680, ["coupon"]],
  ["cooling-bed-sheet", "shopee", 1299, ["lowest"]],
  ["cooling-bed-sheet", "pchome", 1590, ["fast-delivery"]],
  ["cooling-blanket", "momo", 1190, ["coupon"]],
  ["cooling-blanket", "shopee", 890, ["lowest"]],
  ["cooling-blanket", "pchome", 1090, ["fast-delivery"]],
  ["sheet-mask", "momo", 599, ["coupon"]],
  ["sheet-mask", "coupang", 429, ["lowest"]],
  ["sheet-mask", "shopee", 499, ["free-shipping"]],
  ["robot-vacuum", "momo", 25650, ["fast-delivery"]],
  ["robot-vacuum", "biggo", 24990, ["lowest"]],
  ["robot-vacuum", "pchome", 26600, ["official"]],
  ["wet-dry-vacuum", "momo", 6990, ["coupon"]],
  ["wet-dry-vacuum", "biggo", 6890, ["lowest"]],
  ["wet-dry-vacuum", "pchome", 7490, ["fast-delivery"]],
  ["inverter-dehumidifier", "momo", 17900, ["coupon"]],
  ["inverter-dehumidifier", "feebee", 17100, ["lowest"]],
  ["inverter-dehumidifier", "pchome", 18900, ["fast-delivery"]],
  ["cordless-vacuum", "momo", 16900, ["coupon"]],
  ["cordless-vacuum", "biggo", 15880, ["lowest"]],
  ["cordless-vacuum", "pchome", 17900, ["fast-delivery"]],
  ["air-purifier", "momo", 12900, ["coupon"]],
  ["air-purifier", "shopee", 11880, ["lowest"]],
  ["air-purifier", "pchome", 13500, ["fast-delivery"]],
  ["vacuum-storage-bag", "momo", 499, ["coupon"]],
  ["vacuum-storage-bag", "shopee", 329, ["lowest"]],
  ["vacuum-storage-bag", "coupang", 359, ["fast-delivery"]],
  ["lutein", "momo", 990, ["coupon"]],
  ["lutein", "iherb", 760, ["lowest", "cross-border"]],
  ["lutein", "shopee", 880, ["free-shipping"]],
  ["probiotics", "momo", 1280, ["coupon"]],
  ["probiotics", "iherb", 980, ["lowest", "cross-border"]],
  ["probiotics", "coupang", 1090, ["fast-delivery"]],
  ["fish-oil", "momo", 1190, ["coupon"]],
  ["fish-oil", "iherb", 790, ["lowest", "cross-border"]],
  ["fish-oil", "coupang", 990, ["fast-delivery"]],
  ["vitamin-d", "momo", 420, ["coupon"]],
  ["vitamin-d", "iherb", 260, ["lowest", "cross-border"]],
  ["vitamin-d", "shopee", 350, ["free-shipping"]],
  ["chiikawa-blind-box", "brand-store", 450, ["official"]],
  ["chiikawa-blind-box", "shopee", 390, ["lowest"]],
  ["chiikawa-blind-box", "mercari", 520, ["cross-border"]],
  ["labubu", "brand-store", 980, ["official"]],
  ["labubu", "shopee", 1290, ["fast-delivery"]],
  ["labubu", "mercari", 1120, ["lowest", "cross-border"]],
  ["haikyuu-merch", "brand-store", 690, ["official"]],
  ["haikyuu-merch", "shopee", 520, ["lowest"]],
  ["haikyuu-merch", "mercari", 780, ["cross-border"]],
  ["iherb-supplements", "iherb", 980, ["lowest", "cross-border"]],
  ["iherb-supplements", "momo", 1280, ["coupon"]],
  ["iherb-supplements", "shopee", 1180, ["free-shipping"]],
  ["mercari-jp-proxy", "mercari", 1500, ["lowest", "cross-border"]],
  ["mercari-jp-proxy", "shopee", 1680, ["fast-delivery"]],
  ["mercari-jp-proxy", "brand-store", 2200, ["official"]],
  ["1688-household", "shopee", 399, ["fast-delivery"]],
  ["1688-household", "brand-store", 590, ["official"]],
  ["1688-household", "biggo", 320, ["lowest", "cross-border"]],
];

export const offers: Offer[] = offerRows.map(([productSlug, storeId, price, badges]) => {
  const product = products.find((item) => item.slug === productSlug);
  const store = stores.find((item) => item.id === storeId);
  const query = encodeURIComponent(product?.name ?? productSlug);

  return {
    id: `${productSlug}-${storeId}`,
    productSlug,
    storeId,
    title: `${product?.name ?? productSlug} - ${store?.name ?? storeId}`,
    price,
    currency: "TWD",
    url: `${store?.url ?? "https://example.com/"}?q=${query}`,
    fetchedAt: now,
    sourceName: "Curated seed",
    sourceUrl: "https://trends.google.com/trending/rss?geo=TW",
    shippingLabel: badges?.includes("cross-border") ? "可能需國際運費/報關" : "以通路頁面為準",
    badges: badges as Offer["badges"],
  };
});

export const manualTrends: Trend[] = [
  trend("iphone-17", "iPhone 17", "265000+", ["iphone-17-256", "iphone-17-pro-256"]),
  trend("iphone-16", "iPhone 16", "182000+", ["iphone-16-128"]),
  trend("coupang-deals", "酷澎優惠", "237000+", ["face-sunscreen", "sheet-mask", "vacuum-storage-bag"]),
  trend("chiikawa", "吉伊卡哇", "246000+", ["chiikawa-blind-box"]),
  trend("labubu", "Labubu", "135000+", ["labubu"]),
  trend("iherb", "iHerb", "89000+", ["iherb-supplements", "lutein", "fish-oil", "vitamin-d"]),
  trend("cooling-bedding", "涼感床包", "seasonal", ["cooling-bed-sheet", "cooling-blanket"]),
  trend("robot-vacuum", "掃拖機器人", "seasonal", ["robot-vacuum"]),
  trend("wet-dry-vacuum", "洗地機", "seasonal", ["wet-dry-vacuum"]),
  trend("dehumidifier", "除濕機", "21000+", ["inverter-dehumidifier"]),
];

function trend(id: string, keyword: string, approxTraffic: string, relatedProductSlugs: string[]): Trend {
  return {
    id,
    keyword,
    approxTraffic,
    relatedProductSlugs,
    sourceName: "Curated Taiwan trend seed",
    sourceUrl: "https://irvinglab.com/blog/taiwan-google-search-report-2026/",
    observedAt: now,
  };
}

export const storeSeedPlugin: DataPlugin<Store> = {
  id: "seed-stores",
  async collect() {
    return stores;
  },
};

export const productSeedPlugin: DataPlugin<Product> = {
  id: "seed-products",
  async collect() {
    return products;
  },
};

export const offerSeedPlugin: DataPlugin<Offer> = {
  id: "seed-offers",
  async collect() {
    return offers;
  },
};

export const manualTrendPlugin: DataPlugin<Trend> = {
  id: "manual-trends",
  async collect() {
    return manualTrends;
  },
};
