import type {
  WorldCupFixture,
  WorldCupInsight,
  WorldCupMatchup,
  WorldCupPlayer,
  WorldCupSource,
  WorldCupTeam,
} from "./types";

export const worldCupGeneratedAt = "2026-05-22T02:00:00.000Z";

export const worldCupSources: WorldCupSource[] = [
  {
    id: "fifa-worldcup",
    name: "FIFA World Cup 2026",
    url: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026",
    tier: "official",
    usage: "官方賽事、賽程、Match Centre 與賽事新聞。",
    lastChecked: "2026-05-22",
  },
  {
    id: "fifa-training",
    name: "FIFA Training Centre",
    url: "https://www.fifatrainingcentre.com/en/fwc2022/technical-and-tactical-analysis/technical-tactical-overview.php",
    tier: "official",
    usage: "官方技戰術趨勢與歷屆世界盃技術分析。",
    lastChecked: "2026-05-22",
  },
  {
    id: "statsbomb-open",
    name: "StatsBomb Open Data",
    url: "https://blogarchive.statsbomb.com/news/statsbomb-release-free-2022-world-cup-data/",
    tier: "public-data",
    usage: "公開授權的 2022 世界盃 event data 與 360 freeze-frame 背景。",
    lastChecked: "2026-05-22",
  },
  {
    id: "opta-analyst",
    name: "Opta Analyst",
    url: "https://theanalyst.com/competition/fifa-world-cup",
    tier: "trusted-reference",
    usage: "賽事文章、預測模型與統計觀點參考。",
    lastChecked: "2026-05-22",
  },
  {
    id: "sofascore",
    name: "Sofascore World Cup",
    url: "https://www.sofascore.com/football/tournament/world/world-championship/16",
    tier: "trusted-reference",
    usage: "賽程、live scores、standings、球員評分與賽事狀態。",
    lastChecked: "2026-05-22",
  },
  {
    id: "fotmob",
    name: "FotMob World Cup",
    url: "https://www.fotmob.com/leagues/77/overview/world-cup",
    tier: "trusted-reference",
    usage: "賽程、新聞、球隊與球員統計參考。",
    lastChecked: "2026-05-22",
  },
  {
    id: "transfermarkt",
    name: "Transfermarkt World Cup",
    url: "https://www.transfermarkt.com/world-cup/teilnehmer/pokalwettbewerb/FIWC",
    tier: "trusted-reference",
    usage: "參賽隊伍、球員身價、平均年齡與陣容深度參考。",
    lastChecked: "2026-05-22",
  },
  {
    id: "sportmonks",
    name: "Sportmonks World Cup API",
    url: "https://www.sportmonks.com/football-api/world-cup-api/world-cup-2026/",
    tier: "future-api",
    usage: "未來可評估的付費 API；MVP 階段不使用。",
    lastChecked: "2026-05-22",
  },
];

export const worldCupTeams: WorldCupTeam[] = [
  {
    slug: "argentina",
    name: "阿根廷",
    shortName: "ARG",
    confederation: "CONMEBOL",
    status: "qualified",
    fifaTitles: 3,
    bestFinish: "冠軍",
    marketValueLabel: "高身價核心 + 冠軍班底",
    averageAgeLabel: "成熟核心",
    style: "控球與短傳推進之外，也能靠 Messi 周邊跑動、第二線前插與轉換節奏創造機會。",
    strengths: ["大賽經驗完整", "中前場小組配合成熟", "落後時仍有換節奏能力"],
    watchPoints: ["核心老化與出場管理", "右路防守被速度衝擊時的保護", "淘汰賽是否過度依賴單點創造"],
    historicalCycles: [
      { year: 2014, result: "亞軍", note: "防守紀律強，決賽小比分落敗。" },
      { year: 2018, result: "16 強", note: "攻守失衡，後場承壓明顯。" },
      { year: 2022, result: "冠軍", note: "中場平衡與 Messi 最終舞台達到高點。" },
    ],
    keyPlayerSlugs: ["lionel-messi", "julian-alvarez"],
    sourceIds: ["fifa-worldcup", "fifa-training", "transfermarkt"],
  },
  {
    slug: "france",
    name: "法國",
    shortName: "FRA",
    confederation: "UEFA",
    status: "qualified",
    fifaTitles: 2,
    bestFinish: "冠軍",
    marketValueLabel: "世界頂級陣容價值",
    averageAgeLabel: "黃金世代延續",
    style: "能低位吸收壓力，也能用 Mbappe 的速度把防線瞬間拉開。",
    strengths: ["轉換進攻速度頂級", "邊路爆點多", "中後場身體條件強"],
    watchPoints: ["中場控球穩定性", "面對低位密集防守的耐心", "明星球員健康狀態"],
    historicalCycles: [
      { year: 2014, result: "8 強", note: "新世代開始成形。" },
      { year: 2018, result: "冠軍", note: "反擊效率與陣容深度達到頂峰。" },
      { year: 2022, result: "亞軍", note: "傷病仍能進決賽，展示深度。" },
    ],
    keyPlayerSlugs: ["kylian-mbappe"],
    sourceIds: ["fifa-training", "opta-analyst", "transfermarkt"],
  },
  {
    slug: "england",
    name: "英格蘭",
    shortName: "ENG",
    confederation: "UEFA",
    status: "qualified",
    fifaTitles: 1,
    bestFinish: "冠軍",
    marketValueLabel: "Transfermarkt 頂級市場價值",
    averageAgeLabel: "中生代與新星並存",
    style: "前場個人能力強，Bellingham 與 Kane 的連動能決定進攻層次。",
    strengths: ["前場選擇多", "定位球威脅", "中場推進與禁區前決策能力"],
    watchPoints: ["大賽後段保守傾向", "左路與右路攻守平衡", "面對高壓時的出球品質"],
    historicalCycles: [
      { year: 2014, result: "小組賽", note: "早早出局，世代轉換陣痛。" },
      { year: 2018, result: "4 強", note: "定位球與防守結構帶來突破。" },
      { year: 2022, result: "8 強", note: "內容提升，但關鍵球處理仍差一點。" },
    ],
    keyPlayerSlugs: ["harry-kane", "jude-bellingham", "bukayo-saka"],
    sourceIds: ["transfermarkt", "opta-analyst"],
  },
  {
    slug: "brazil",
    name: "巴西",
    shortName: "BRA",
    confederation: "CONMEBOL",
    status: "qualified",
    fifaTitles: 5,
    bestFinish: "冠軍",
    marketValueLabel: "高身價邊鋒群",
    averageAgeLabel: "核心進入成熟期",
    style: "邊路爆破、個人單挑與快速轉移仍是最具威脅的武器。",
    strengths: ["一對一能力強", "前場選擇豐富", "歷史底蘊與比賽經驗"],
    watchPoints: ["中場控制力", "面對歐洲強隊的防守細節", "淘汰賽抗壓"],
    historicalCycles: [
      { year: 2014, result: "4 強", note: "主場高壓下防線崩盤。" },
      { year: 2018, result: "8 強", note: "個人能力強，但關鍵場效率不足。" },
      { year: 2022, result: "8 強", note: "控場時間長，卻被克羅埃西亞拖入點球。" },
    ],
    keyPlayerSlugs: ["vinicius-junior"],
    sourceIds: ["fifa-worldcup", "transfermarkt"],
  },
  {
    slug: "spain",
    name: "西班牙",
    shortName: "ESP",
    confederation: "UEFA",
    status: "qualified",
    fifaTitles: 1,
    bestFinish: "冠軍",
    marketValueLabel: "新世代高價值陣容",
    averageAgeLabel: "年輕化",
    style: "以控球、位置輪轉與邊路創造為主，年輕球員能提高節奏。",
    strengths: ["控球穩定", "中場技術深度", "邊路新星創造力"],
    watchPoints: ["缺少傳統終結點時的效率", "面對反擊的保護", "年輕球員大賽穩定性"],
    historicalCycles: [
      { year: 2014, result: "小組賽", note: "黃金世代退潮。" },
      { year: 2018, result: "16 強", note: "控球有餘，穿透不足。" },
      { year: 2022, result: "16 強", note: "傳控風格鮮明，但終結效率受質疑。" },
    ],
    keyPlayerSlugs: ["lamine-yamal", "pedri"],
    sourceIds: ["transfermarkt", "opta-analyst"],
  },
  {
    slug: "usa",
    name: "美國",
    shortName: "USA",
    confederation: "CONCACAF",
    status: "host",
    fifaTitles: 0,
    bestFinish: "4 強",
    marketValueLabel: "主場紅利 + 歐洲聯賽球員",
    averageAgeLabel: "年輕核心",
    style: "靠體能、速度與高強度轉換製造壓力，主場氣氛會放大能量。",
    strengths: ["主場優勢", "年輕速度", "中前場衝刺能力"],
    watchPoints: ["破密集能力", "中鋒穩定性", "淘汰賽經驗"],
    historicalCycles: [
      { year: 2014, result: "16 強", note: "高強度與門將發揮令人印象深刻。" },
      { year: 2018, result: "未參賽", note: "資格賽失利後重建。" },
      { year: 2022, result: "16 強", note: "年輕核心回到世界盃舞台。" },
    ],
    keyPlayerSlugs: ["christian-pulisic"],
    sourceIds: ["fifa-worldcup", "sofascore", "fotmob"],
  },
  {
    slug: "mexico",
    name: "墨西哥",
    shortName: "MEX",
    confederation: "CONCACAF",
    status: "host",
    group: "A",
    fifaTitles: 0,
    bestFinish: "8 強",
    marketValueLabel: "主場焦點隊",
    averageAgeLabel: "經驗型陣容",
    style: "主場氛圍、逼搶與邊路節奏是主要能量來源。",
    strengths: ["主場開幕戰話題", "大賽經驗", "邊路推進"],
    watchPoints: ["進攻穩定性", "世代交替", "壓力下的決策"],
    historicalCycles: [
      { year: 2014, result: "16 強", note: "穩定小組出線，但止步淘汰賽。" },
      { year: 2018, result: "16 強", note: "擊敗德國是代表作。" },
      { year: 2022, result: "小組賽", note: "連續出線紀錄中斷。" },
    ],
    keyPlayerSlugs: ["santiago-gimenez"],
    sourceIds: ["fifa-worldcup", "sofascore"],
  },
  {
    slug: "japan",
    name: "日本",
    shortName: "JPN",
    confederation: "AFC",
    status: "qualified",
    fifaTitles: 0,
    bestFinish: "16 強",
    marketValueLabel: "旅歐球員深度提升",
    averageAgeLabel: "成熟且輪換完整",
    style: "防守組織嚴謹，轉換時能快速找到肋部與弱側空間。",
    strengths: ["戰術紀律", "旅歐球員深度", "反擊效率"],
    watchPoints: ["面對身體優勢隊伍的定位球", "禁區終結", "小組賽節奏管理"],
    historicalCycles: [
      { year: 2014, result: "小組賽", note: "控球企圖明顯但效率不足。" },
      { year: 2018, result: "16 強", note: "對比利時差點爆冷。" },
      { year: 2022, result: "16 強", note: "擊敗德國與西班牙，證明戰術執行力。" },
    ],
    keyPlayerSlugs: ["takefusa-kubo", "kaoru-mitoma"],
    sourceIds: ["fifa-worldcup", "sofascore", "transfermarkt"],
  },
];

export const worldCupPlayers: WorldCupPlayer[] = [
  {
    slug: "kylian-mbappe",
    name: "Kylian Mbappe",
    teamSlug: "france",
    position: "FWD",
    club: "Real Madrid",
    status: "final-squad-pending",
    role: "法國轉換進攻的第一張王牌。",
    summary: "他的速度會改變對手防線高度，任何高位壓迫都要先考慮身後空間。",
    strengths: ["左側肋部衝刺", "反擊第一拍", "大賽終結能力"],
    matchupFocus: "對上速度不足的右後衛時，法國可以把比賽變成大片空間的單點攻防。",
    sourceIds: ["fifa-training", "opta-analyst", "transfermarkt"],
  },
  {
    slug: "jude-bellingham",
    name: "Jude Bellingham",
    teamSlug: "england",
    position: "MID",
    club: "Real Madrid",
    status: "final-squad-pending",
    role: "英格蘭中前場的節奏與禁區前插核心。",
    summary: "他不是只做傳球的中場，而是會把第二波進攻帶進禁區的人。",
    strengths: ["禁區前插", "抗壓拿球", "攻守轉換判斷"],
    matchupFocus: "若對手防守中場被 Kane 拉出，Bellingham 的後上會是最大問題。",
    sourceIds: ["opta-analyst", "transfermarkt"],
  },
  {
    slug: "harry-kane",
    name: "Harry Kane",
    teamSlug: "england",
    position: "FWD",
    club: "Bayern Munich",
    status: "final-squad-pending",
    role: "英格蘭的終結點，也是回撤串聯點。",
    summary: "Kane 會讓中衛猶豫要不要跟出來，這會影響英格蘭邊路與中場前插。",
    strengths: ["禁區終結", "回撤傳球", "定位球與點球穩定性"],
    matchupFocus: "對手中衛若跟出來，身後空間會給 Saka 或 Bellingham 利用。",
    sourceIds: ["transfermarkt", "opta-analyst"],
  },
  {
    slug: "vinicius-junior",
    name: "Vinicius Junior",
    teamSlug: "brazil",
    position: "FWD",
    club: "Real Madrid",
    status: "final-squad-pending",
    role: "巴西左路一對一的主要爆點。",
    summary: "他能把原本普通的邊路進攻變成需要協防的高危場景。",
    strengths: ["速度突破", "弱側接應", "禁區左側製造混亂"],
    matchupFocus: "如果對手右後衛缺乏速度支援，巴西會很自然地把球導向他這側。",
    sourceIds: ["transfermarkt", "fotmob"],
  },
  {
    slug: "lamine-yamal",
    name: "Lamine Yamal",
    teamSlug: "spain",
    position: "FWD",
    club: "Barcelona",
    status: "final-squad-pending",
    role: "西班牙右路創造力與節奏變化來源。",
    summary: "年輕但成熟度高，能用內切、傳中與節奏停頓改變防守重心。",
    strengths: ["右路內切", "最後一傳", "吸引包夾後分球"],
    matchupFocus: "對手左後衛若只退不搶，西班牙會取得很舒服的組織角度。",
    sourceIds: ["transfermarkt", "fotmob"],
  },
  {
    slug: "lionel-messi",
    name: "Lionel Messi",
    teamSlug: "argentina",
    position: "FWD",
    club: "Inter Miami",
    status: "watchlist",
    role: "阿根廷的節奏與最後一傳象徵。",
    summary: "參賽狀態需等待正式名單；若出場，他仍是低節奏局面中的解題者。",
    strengths: ["肋部接球", "定位球", "最後一傳"],
    matchupFocus: "對手是否用防守中場貼身保護禁區前，是阿根廷進攻空間的關鍵。",
    sourceIds: ["fifa-training", "transfermarkt"],
  },
  {
    slug: "julian-alvarez",
    name: "Julian Alvarez",
    teamSlug: "argentina",
    position: "FWD",
    club: "Atletico Madrid",
    status: "final-squad-pending",
    role: "前場壓迫與無球跑動的重要拼圖。",
    summary: "他讓阿根廷前場不只靠持球創造，也能靠壓迫與跑動製造二次機會。",
    strengths: ["前場壓迫", "斜向跑動", "禁區補點"],
    matchupFocus: "如果對手中衛出球慢，Alvarez 能讓比賽變成高壓回收。",
    sourceIds: ["transfermarkt", "fifa-training"],
  },
  {
    slug: "christian-pulisic",
    name: "Christian Pulisic",
    teamSlug: "usa",
    position: "FWD",
    club: "AC Milan",
    status: "final-squad-pending",
    role: "美國隊最重要的前場持球與終結點。",
    summary: "主場世界盃會放大他的能量，美國需要他把轉換打成真正威脅。",
    strengths: ["邊路內切", "反擊推進", "禁區邊緣射門"],
    matchupFocus: "對手若把壓迫推高，美國最直接的出口通常會找他。",
    sourceIds: ["sofascore", "fotmob"],
  },
  {
    slug: "takefusa-kubo",
    name: "Takefusa Kubo",
    teamSlug: "japan",
    position: "FWD",
    club: "Real Sociedad",
    status: "final-squad-pending",
    role: "日本右側進攻的創造力來源。",
    summary: "Kubo 能在狹小空間處理球，讓日本不只能反擊，也能控球找破口。",
    strengths: ["右路接球轉身", "肋部分球", "定位球變化"],
    matchupFocus: "若對手邊後衛壓得太深，他的半空間拿球會成為日本主要出口。",
    sourceIds: ["transfermarkt", "fotmob"],
  },
  {
    slug: "kaoru-mitoma",
    name: "Kaoru Mitoma",
    teamSlug: "japan",
    position: "FWD",
    club: "Brighton",
    status: "final-squad-pending",
    role: "日本左路一對一與後段變速武器。",
    summary: "他擅長等防守者重心先交出來，再用第一步突破創造傳中或切入。",
    strengths: ["左路突破", "節奏變化", "替補衝擊"],
    matchupFocus: "對手右路若缺少協防，日本下半場可能把他當作節奏改變點。",
    sourceIds: ["fotmob", "transfermarkt"],
  },
  {
    slug: "santiago-gimenez",
    name: "Santiago Gimenez",
    teamSlug: "mexico",
    position: "FWD",
    club: "AC Milan",
    status: "final-squad-pending",
    role: "墨西哥最需要兌現的禁區終結點。",
    summary: "主場期待會很高，但墨西哥真正需要的是他把控球轉成禁區成果。",
    strengths: ["禁區跑位", "第一時間射門", "背身接應"],
    matchupFocus: "如果墨西哥邊路能穩定送球，他和中衛的搶點會很關鍵。",
    sourceIds: ["sofascore", "transfermarkt"],
  },
  {
    slug: "pedri",
    name: "Pedri",
    teamSlug: "spain",
    position: "MID",
    club: "Barcelona",
    status: "final-squad-pending",
    role: "西班牙中場節奏與短傳連接器。",
    summary: "他讓西班牙的控球不是橫向循環，而是能找到下一個推進角度。",
    strengths: ["中場轉向", "小空間配合", "節奏控制"],
    matchupFocus: "對手若只守禁區不壓他，西班牙會逐步把球送進高價值區域。",
    sourceIds: ["transfermarkt", "opta-analyst"],
  },
];

export const worldCupFixtures: WorldCupFixture[] = [
  {
    slug: "mexico-host-opener",
    stage: "Group A",
    homeTeamSlug: "mexico",
    awayTeamSlug: "usa",
    venue: "North America opening week",
    kickoffLabel: "2026 開幕週",
    note: "正式賽程與對手以 FIFA 公告為準；MVP 先以北美主辦國焦點做預熱卡。",
    sourceIds: ["fifa-worldcup", "sofascore"],
  },
  {
    slug: "france-brazil-watch",
    stage: "Potential knockout storyline",
    homeTeamSlug: "france",
    awayTeamSlug: "brazil",
    venue: "Knockout scenario",
    kickoffLabel: "情境預熱",
    note: "速度型邊路與轉換進攻的高話題對位。",
    sourceIds: ["fifa-training", "transfermarkt"],
  },
];

export const worldCupMatchups: WorldCupMatchup[] = [
  {
    slug: "france-vs-brazil-wide-threats",
    title: "法國速度轉換 vs 巴西邊路爆破",
    teamSlugs: ["france", "brazil"],
    stage: "高話題淘汰賽情境",
    summary: "兩隊都能靠邊路速度直接改變比賽，差異在法國更偏轉換，巴西更偏單點爆破。",
    tempoRead: "如果比賽開放，法國反擊效率會被放大；如果節奏慢，巴西左路單挑會更重要。",
    watchSignals: ["雙方右後衛是否能得到保護", "中場丟球後的第一時間反搶", "誰能把邊路優勢轉成禁區觸球"],
    positionDuels: [
      { label: "Mbappe vs 右側防線", summary: "高位防守會讓身後空間變成最大風險。" },
      { label: "Vinicius vs 協防中場", summary: "單防很難，重點是第二名防守者何時補上。" },
    ],
    playerSlugs: ["kylian-mbappe", "vinicius-junior"],
    sourceIds: ["fifa-training", "opta-analyst"],
  },
  {
    slug: "england-vs-spain-midfield-control",
    title: "英格蘭禁區前插 vs 西班牙控球節奏",
    teamSlugs: ["england", "spain"],
    stage: "強隊中場對位",
    summary: "英格蘭希望用 Bellingham 與 Kane 的縱向連動打穿中路；西班牙會用傳控把比賽壓進半場。",
    tempoRead: "節奏越慢越像西班牙的比賽；節奏越斷裂，英格蘭的禁區前插越危險。",
    watchSignals: ["Kane 回撤時誰跟防", "Bellingham 是否能進入禁區", "Yamal 右路能否吸引包夾"],
    positionDuels: [
      { label: "Bellingham vs 西班牙防守中場", summary: "後插上是英格蘭最高價值的進攻方式之一。" },
      { label: "Yamal vs 英格蘭左路", summary: "西班牙能否拉開空間，取決於右路創造力。" },
    ],
    playerSlugs: ["jude-bellingham", "harry-kane", "lamine-yamal", "pedri"],
    sourceIds: ["opta-analyst", "transfermarkt"],
  },
  {
    slug: "japan-vs-usa-transition-duel",
    title: "日本紀律反擊 vs 美國主場能量",
    teamSlugs: ["japan", "usa"],
    stage: "黑馬與主場焦點",
    summary: "這是一種高強度、低容錯的對位：日本靠紀律與弱側轉移，美國靠主場與速度衝擊。",
    tempoRead: "如果美國過早把防線推高，日本的弱側切換會很有威脅；如果日本被迫低位防守太久，Pulisic 的持球會增加壓力。",
    watchSignals: ["日本邊路換位速度", "美國前場壓迫是否有效", "定位球與第二點保護"],
    positionDuels: [
      { label: "Pulisic vs 日本右路保護", summary: "美國需要把個人突破轉成禁區觸球。" },
      { label: "Kubo/Mitoma vs 美國邊後衛", summary: "日本的節奏變化多半來自兩側邊鋒。" },
    ],
    playerSlugs: ["christian-pulisic", "takefusa-kubo", "kaoru-mitoma"],
    sourceIds: ["sofascore", "fotmob"],
  },
];

export const worldCupInsights: WorldCupInsight[] = [
  {
    id: "data-policy",
    title: "資料先求可驗證，不求看起來即時",
    category: "data-policy",
    body: "MVP 階段使用官方與公開資料，沒有付費 API，也不使用 odds。若資料不是官方最終名單，頁面會標示為 watchlist 或 final-squad-pending。",
    sourceIds: ["fifa-worldcup", "sportmonks"],
  },
  {
    id: "wide-areas",
    title: "邊路仍是現代世界盃的高價值區",
    category: "tactical-trend",
    body: "FIFA Training Centre 在 2022 技術分析中提到，crosses 與 wide areas 的影響上升。這讓邊鋒、邊後衛與中鋒搶點成為預熱分析重點。",
    sourceIds: ["fifa-training"],
  },
  {
    id: "squad-depth",
    title: "48 隊賽制讓陣容深度更重要",
    category: "team-form",
    body: "2026 賽制擴張後，賽程更長，淘汰賽多一輪。除了先發強度，替補與輪換品質會直接影響後段比賽。",
    sourceIds: ["fifa-worldcup", "transfermarkt"],
  },
  {
    id: "star-watch",
    title: "明星球員不是只看名氣，要看位置影響",
    category: "player-watch",
    body: "同樣是明星，邊鋒會影響防線高度，中場會影響控球節奏，中鋒會影響中衛站位。頁面要把明星放回戰術語境裡。",
    sourceIds: ["opta-analyst", "fifa-training"],
  },
];
